# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('win', models.FloatField()),
                ('draw', models.FloatField()),
                ('loose', models.FloatField()),
                ('is_finished', models.BooleanField()),
            ],
        ),
    ]
