# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20171127_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='picture',
        ),
        migrations.AlterField(
            model_name='comment',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.Match'),
        ),
    ]
