# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20171128_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='bet',
            new_name='draw_bet',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='is_draw',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='is_loose',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='is_win',
        ),
        migrations.AddField(
            model_name='bet',
            name='loose_bet',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bet',
            name='win_bet',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bet',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='users.Match'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.Match'),
        ),
    ]
