# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20171128_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='total_bet',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bet',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='users.Match'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.Match'),
        ),
    ]
